-- ============================================================
-- Peer Interview Reports Migration — Mirracle
-- Run AFTER migrations.sql (public.profiles must exist)
--
-- Persists reports generated by PeerMeet's Gemini pipeline. Writes flow in
-- through the FastAPI /internal/peer-reports webhook using the service-role
-- key (bypasses RLS). Reads go through the authenticated dashboard: RLS
-- restricts SELECT to the report's own subject.
-- ============================================================

create table if not exists public.peer_interview_reports (
  id                    uuid         primary key default gen_random_uuid(),
  room_id               text         not null,
  student_id            uuid         not null references public.profiles(id) on delete cascade,
  partner_student_id    uuid         references public.profiles(id) on delete set null,
  role                  text         not null check (role in ('candidate','interviewer')),
  overall_score         numeric,
  technical_score       numeric,
  communication_score   numeric,
  confidence_score      numeric,
  problem_solving_score numeric,
  topics_covered        text[],
  strengths             text[],
  weaknesses            text[],
  question_timeline     jsonb,
  suggestions           text[],
  final_recommendation  text,
  created_at            timestamptz  not null default now()
);

create index if not exists idx_peer_interview_reports_student_created
  on public.peer_interview_reports(student_id, created_at desc);
create index if not exists idx_peer_interview_reports_room
  on public.peer_interview_reports(room_id);

alter table public.peer_interview_reports enable row level security;

-- Service-role (backend webhook) can do everything.
create policy "service_role_all_peer_interview_reports"
  on public.peer_interview_reports
  for all
  using      (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

-- Authenticated students can read only their OWN reports. No INSERT/UPDATE/
-- DELETE policy — writes must come from the service-role webhook.
create policy "student_select_own_peer_interview_reports"
  on public.peer_interview_reports
  for select
  using (auth.uid() = student_id);
